theme: jekyll-theme-midnight

title: BASIC-DOS
domain: basicdos.com
description: "BASIC-DOS is like a doughnut: small and tasty."
author: Jeff Parsons
data_dir: configs
left_brace: "{"
right_brace: "}"
encoding: UTF-8
root: /tasty

github:
  owner_name: "jeffpar"
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/basicdos

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .history
  - "**/archive"
  - gulpfile.js
  - node_modules
  - "package*.json"
  - "**/rbil"
  - "*.OBJ"
  - "*.COM"
