title: BASIC-DOS
domain: basicdos.com
description: A PCjs Retro-Programming Project
author: Jeff Parsons
twitter_id: jeffpar
data_dir: configs
left_brace: "{"
right_brace: "}"
encoding: UTF-8
google_analytics: UA-49658648-4
theme: jekyll-theme-midnight
betaurl: /maplebar

github:
  owner_name: jeffpar
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/basicdos

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - "package*.json"
  - "**/archive"
  - "**/bdsrc"
  - /.history
  - /node_modules
