theme: jekyll-theme-midnight

title: BASIC-DOS
domain: basicdos.com
description: "A PCjs Retro-Programming Project"
author: Jeff Parsons
data_dir: configs
left_brace: "{"
right_brace: "}"
encoding: UTF-8
google_analytics: UA-49658648-4

github:
  owner_name: "jeffpar"
  owner_url: https://github.com/jeffpar
  repository_url: https://github.com/jeffpar/basicdos

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .history
  - "**/archive"
  - gulpfile.js
  - node_modules
  - "package*.json"
  - "*.OBJ"
  - "*.COM"
